export const PERMISSIONS = {
  // Administration
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',

  // Accounts
  VIEW_ACCOUNTS: 'VIEW_ACCOUNTS',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  EDIT_ACCOUNT: 'EDIT_ACCOUNT',
  DEACTIVATE_ACCOUNT: 'DEACTIVATE_ACCOUNT',
  LOOKUP_ACCOUNTS: 'LOOKUP_ACCOUNTS',

  // Cost Center
  VIEW_COST_CENTER: 'VIEW_COST_CENTER',
  CREATE_COST_CENTER: 'CREATE_COST_CENTER',
  EDIT_COST_CENTER: 'EDIT_COST_CENTER',
  DEACTIVATE_COST_CENTER: 'DEACTIVATE_COST_CENTER',
  LOOKUP_COST_CENTER: 'LOOKUP_COST_CENTER',

  // Journal
  VIEW_JOURNAL: 'VIEW_JOURNAL',
  CREATE_JOURNAL: 'CREATE_JOURNAL',
  POST_JOURNAL: 'POST_JOURNAL',
  REVERSE_JOURNAL: 'REVERSE_JOURNAL',
  DELETE_JOURNAL: 'DELETE_JOURNAL',
  APPROVE_JOURNAL: 'APPROVE_JOURNAL',
  REJECT_JOURNAL: 'REJECT_JOURNAL',
  RETURN_JOURNAL: 'RETURN_JOURNAL',
  VIEW_APPROVAL_QUEUE: 'VIEW_APPROVAL_QUEUE',

  // Party
  VIEW_PARTY: 'VIEW_PARTY',
  CREATE_PARTY: 'CREATE_PARTY',
  EDIT_PARTY: 'EDIT_PARTY',
  DEACTIVATE_PARTY: 'DEACTIVATE_PARTY',
  LOOKUP_PARTIES: 'LOOKUP_PARTIES',

  // Invoice
  VIEW_INVOICE: 'VIEW_INVOICE',
  CREATE_INVOICE: 'CREATE_INVOICE',
  EDIT_INVOICE: 'EDIT_INVOICE',
  APPROVE_INVOICE: 'APPROVE_INVOICE',
  REJECT_INVOICE: 'REJECT_INVOICE',
  RETURN_INVOICE: 'RETURN_INVOICE',
  POST_INVOICE: 'POST_INVOICE',
  CANCEL_INVOICE: 'CANCEL_INVOICE',

  // Vendor Bill
  VIEW_VENDOR_BILL: 'VIEW_VENDOR_BILL',
  CREATE_VENDOR_BILL: 'CREATE_VENDOR_BILL',
  EDIT_VENDOR_BILL: 'EDIT_VENDOR_BILL',
  APPROVE_VENDOR_BILL: 'APPROVE_VENDOR_BILL',
  REJECT_VENDOR_BILL: 'REJECT_VENDOR_BILL',
  RETURN_VENDOR_BILL: 'RETURN_VENDOR_BILL',
  POST_VENDOR_BILL: 'POST_VENDOR_BILL',
  CANCEL_VENDOR_BILL: 'CANCEL_VENDOR_BILL',

  // Expense
  VIEW_EXPENSE: 'VIEW_EXPENSE',
  CREATE_EXPENSE: 'CREATE_EXPENSE',
  CANCEL_EXPENSE: 'CANCEL_EXPENSE',

  // Recurring Expense
  VIEW_RECURRING_EXPENSE: 'VIEW_RECURRING_EXPENSE',
  CREATE_RECURRING_EXPENSE: 'CREATE_RECURRING_EXPENSE',
  EDIT_RECURRING_EXPENSE: 'EDIT_RECURRING_EXPENSE',

  // Payment
  VIEW_PAYMENT: 'VIEW_PAYMENT',
  CREATE_PAYMENT: 'CREATE_PAYMENT',
  APPROVE_PAYMENT: 'APPROVE_PAYMENT',
  REJECT_PAYMENT: 'REJECT_PAYMENT',
  RETURN_PAYMENT: 'RETURN_PAYMENT',
  POST_PAYMENT: 'POST_PAYMENT',
  CANCEL_PAYMENT: 'CANCEL_PAYMENT',

  // Banking
  VIEW_BANKING: 'VIEW_BANKING',
  CREATE_BANKING: 'CREATE_BANKING',
  EDIT_BANKING: 'EDIT_BANKING',

  // Budget
  VIEW_BUDGET: 'VIEW_BUDGET',
  CREATE_BUDGET: 'CREATE_BUDGET',
  EDIT_BUDGET: 'EDIT_BUDGET',
  DELETE_BUDGET: 'DELETE_BUDGET',
  ACTIVATE_BUDGET: 'ACTIVATE_BUDGET',
  CLOSE_BUDGET: 'CLOSE_BUDGET',
  VIEW_BUDGET_REPORT: 'VIEW_BUDGET_REPORT',

  // Fixed Asset
  VIEW_FIXED_ASSET: 'VIEW_FIXED_ASSET',
  CREATE_FIXED_ASSET: 'CREATE_FIXED_ASSET',
  EDIT_FIXED_ASSET: 'EDIT_FIXED_ASSET',
  RUN_DEPRECIATION: 'RUN_DEPRECIATION',
  DISPOSE_FIXED_ASSET: 'DISPOSE_FIXED_ASSET',

  // Reports
  VIEW_LEDGER: 'VIEW_LEDGER',
  VIEW_TRIAL_BALANCE: 'VIEW_TRIAL_BALANCE',
  VIEW_REPORT: 'VIEW_REPORT',

  // Audit
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',

  // Fiscal Year
  VIEW_FISCAL_YEAR: 'VIEW_FISCAL_YEAR',
  CREATE_FISCAL_YEAR: 'CREATE_FISCAL_YEAR',
  EDIT_FISCAL_YEAR: 'EDIT_FISCAL_YEAR',
  ACTIVATE_FISCAL_YEAR: 'ACTIVATE_FISCAL_YEAR',
  CLOSE_FISCAL_YEAR: 'CLOSE_FISCAL_YEAR',
  DELETE_FISCAL_YEAR: 'DELETE_FISCAL_YEAR',

  // Accounting Period
  VIEW_ACCOUNTING_PERIOD: 'VIEW_ACCOUNTING_PERIOD',
  CREATE_ACCOUNTING_PERIOD: 'CREATE_ACCOUNTING_PERIOD',
  EDIT_ACCOUNTING_PERIOD: 'EDIT_ACCOUNTING_PERIOD',
  OPEN_ACCOUNTING_PERIOD: 'OPEN_ACCOUNTING_PERIOD',
  CLOSE_ACCOUNTING_PERIOD: 'CLOSE_ACCOUNTING_PERIOD',
  DELETE_ACCOUNTING_PERIOD: 'DELETE_ACCOUNTING_PERIOD',

  // Credit Note
  VIEW_CREDIT_NOTE: 'VIEW_CREDIT_NOTE',
  CREATE_CREDIT_NOTE: 'CREATE_CREDIT_NOTE',
  EDIT_CREDIT_NOTE: 'EDIT_CREDIT_NOTE',
  APPROVE_CREDIT_NOTE: 'APPROVE_CREDIT_NOTE',
  POST_CREDIT_NOTE: 'POST_CREDIT_NOTE',
  CANCEL_CREDIT_NOTE: 'CANCEL_CREDIT_NOTE',
  DELETE_CREDIT_NOTE: 'DELETE_CREDIT_NOTE',

  // Debit Note
  VIEW_DEBIT_NOTE: 'VIEW_DEBIT_NOTE',
  CREATE_DEBIT_NOTE: 'CREATE_DEBIT_NOTE',
  EDIT_DEBIT_NOTE: 'EDIT_DEBIT_NOTE',
  APPROVE_DEBIT_NOTE: 'APPROVE_DEBIT_NOTE',
  POST_DEBIT_NOTE: 'POST_DEBIT_NOTE',
  CANCEL_DEBIT_NOTE: 'CANCEL_DEBIT_NOTE',
  DELETE_DEBIT_NOTE: 'DELETE_DEBIT_NOTE',
} as const;

export type PermissionCode = typeof PERMISSIONS[keyof typeof PERMISSIONS];
