package com.nexaerp.report;

public enum CashFlowLineItem {
    CUSTOMER_RECEIPTS,
    SUPPLIER_PAYMENTS,
    OPERATING_EXPENSES,
    TAX_PAYMENTS,
    INTEREST_RECEIVED,
    INTEREST_PAID,
    FIXED_ASSET_PURCHASE,
    FIXED_ASSET_DISPOSAL,
    CAPITAL_INTRODUCED,
    LOAN_PROCEEDS,
    LOAN_REPAYMENTS,
    OWNER_WITHDRAWALS,
    OTHER_OPERATING,
    OTHER_INVESTING,
    OTHER_FINANCING,
    UNCLASSIFIED
}
