package com.nexaerp.pdf.common;

import com.itextpdf.kernel.pdf.canvas.draw.SolidLine;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.LineSeparator;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.properties.TextAlignment;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public final class PdfFooter {

    private PdfFooter() {}

    public static void add(Document doc) {
        doc.add(new LineSeparator(new SolidLine(0.5f))
                .setMarginTop(18)
                .setMarginBottom(8));

        doc.add(new Paragraph(
                "Generated by NexaERP on " +
                        LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd MMM yyyy hh:mm a"))
        )
                .setFontSize(8)
                .setFontColor(PdfConstants.MUTED)
                .setTextAlignment(TextAlignment.CENTER));
    }
}